### ISSUE TITLE
Error when increasing the experiment duration

### ISSUE THREAD

**Issue by carlossvg** [ros-realtime/reference-system#102]
**Describe the bug**

I get an error when increasing the experiment duration to 120 seconds. 

**To Reproduce**
1. Use the latest RPI4 image https://github.com/ros-realtime/ros-realtime-rpi4-image/releases/tag/rpi4_ros2_galactic_v5.4.106-rt54-raspi-arm64-lttng
2. Increase run time to 120s https://github.com/ros-realtime/reference-system/blob/main/autoware_reference_system/CMakeLists.txt#L84
3. Build and run the test

```
 benchmark
  <<< failure message
    [INFO] [rclcpp]: Currently used middleware can't loan messages. Local allocator will be used.
    Terminated
    Attaching to process 11820
    Process finished (120.40 seconds)
    Traceback (most recent call last):
      File "/home/ubuntu/workspace/install/autoware_reference_system/share/autoware_reference_system/scripts/benchmark.py", line 65, in <module>
        generate_trace(trace_type, exe, rmw=rmw, runtime_sec=runtime, **common_args)
      File "/home/ubuntu/workspace/install/reference_system/lib/python3.8/site-packages/reference_system_py/benchmark.py", line 237, in generate_trace
        return generate_memory_trace(*args, **kwargs)
      File "/home/ubuntu/workspace/install/reference_system/lib/python3.8/site-packages/reference_system_py/benchmark.py", line 232, in generate_memory_trace
        tracerprocess.wait(2)
      File "/usr/lib/python3.8/subprocess.py", line 1083, in wait
        return self._wait(timeout=timeout)
      File "/usr/lib/python3.8/subprocess.py", line 1798, in _wait
        raise TimeoutExpired(self.args, timeout)
    subprocess.TimeoutExpired: Command 'psrecord --include-children --log /home/ubuntu/.ros/benchmark_autoware_reference_system/2022-04-24-14-11-59/120s/rmw_cyclonedds_cpp/autoware_default_singlethreaded/memory_log.txt --plot /home/ubuntu/.ros/benchmark_autoware_reference_system/2022-04-24-14-11-59/120s/rmw_cyclonedds_cpp/autoware_default_singlethreaded/memory_log.png 11820 ' timed out after 2 seconds
  >>>
```

**Comment by carlossvg** [comment]
@flynneva I increased the timeout to 20 seconds and I'm able to run a 120s test sucessfully in the RPI. I wonder if for higher durations this will be enough. I remember that tracetools analysis took too long for long duration tracing sessions. Anyways, I will create a PR increasing the timeout to 20s if this is fine for you.
