### ISSUE TITLE
Error: PosixPath' object is not iterable

### ISSUE THREAD

**Issue by carlossvg** [ros-realtime/reference-system#138]
**Describe the bug**

I'm getting an error when running the benchmark:

```
python3 $(ros2 pkg prefix --share autoware_reference_system)/scripts/benchmark.py 5 autoware_default_singlethreaded
Attaching to process 9812
[INFO] [rclcpp]: Currently used middleware can't loan messages. Local allocator will be used.
Terminated
Process finished (5.31 seconds)
Output report to /home/ubuntu/.ros/benchmark_autoware_reference_system/2022-06-16-13-25-12/5s/rmw_cyclonedds_cpp/autoware_default_singlethreaded/memory_and_cpu_usage_report.html
[INFO] [rclcpp]: Currently used middleware can't loan messages. Local allocator will be used.
Terminated
Template file was not found: cfg/report_template.md
Falling back to default: /home/ubuntu/workspace/install/reference_system/share/reference_system/cfg/memory_report_template.md
Traceback (most recent call last):
  File "/home/ubuntu/workspace/install/autoware_reference_system/share/autoware_reference_system/scripts/benchmark.py", line 72, in <module>
    generate_summary_report(
  File "/home/ubuntu/workspace/install/reference_system/lib/python3.8/site-packages/reference_system_py/report.py", line 147, in generate_summary_report
    output_report = fill_in_template(
  File "/home/ubuntu/workspace/install/reference_system/lib/python3.8/site-packages/reference_system_py/report.py", line 111, in fill_in_template
    loader=FileSystemLoader(template_directory),
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 163, in __init__
    self.searchpath = list(searchpath)
TypeError: 'PosixPath' object is not iterable
```

**To Reproduce**
1. Follow the build instructions from the documentation
2. Source
3. Execute command or colcon test

**Desktop (please complete the following information):**
 - OS: Thinkpad+ADE
 - RPI4 with RT image

**Comment by flynneva** [comment]
@carlossvg ah shoot this is probably a bug I introduced with the current switch to templates.

The error is that it expects a string instead of a path link.Path object I think.

I'll fix this in a pr in a bit.
